name: charmed-mysql # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '8.0.32-0' # just for humans, typically '1.2+git' or '1.3.2'
summary: MySQL server in a snap. # 79 char long summary
description: |
  The MySQL software delivers a very fast, multithreaded, multi-user,
  and robust SQL (Structured Query Language) database server. MySQL
  Server is intended for mission-critical, heavy-load production
  systems as well as for embedding into mass-deployed software.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

system-usernames:
  snap_daemon: shared

package-repositories:
  - type: apt
    components:
      - mysql-8.0
      - mysql-tools
    suites:
      - jammy
    key-id: 859BE8D7C586F538430B19C2467B942D3A79BD29
    url: http://repo.mysql.com/apt/ubuntu/
  - type: apt
    components:
      - main
    suites:
      - jammy
    key-id: 4D1BB29D63D98E422B2113B19334A25F8507EFA5
    url: http://repo.percona.com/percona/apt

layout:
  /var/lib/mysql-files:
    bind: $SNAP_COMMON/var/lib/mysql-files
  /usr/lib/mysqlrouter:
    symlink: $SNAP/usr/lib/mysqlrouter
  /etc/mysqlrouter:
    bind: $SNAP_DATA/etc/mysqlrouter
  /var/lib/mysqlrouter:
    bind: $SNAP_COMMON/var/lib/mysqlrouter
  /var/log/mysqlrouter:
    bind: $SNAP_COMMON/var/log/mysqlrouter


hooks:
  install:
    plugs:
      - network
      - network-bind
  configure:
    plugs:
      - network

slots:
  logs:
    interface: content
    source:
      read:
        - $SNAP_COMMON/var/log/mysql

apps:
  mysql:
    command: usr/bin/mysql
    plugs:
      - network
  mysqld:
    command: start-mysqld.sh
    daemon: simple
    install-mode: disable
    plugs:
      - network
      - network-bind
  mysqlsh:
    command: usr/bin/mysqlsh
    plugs:
      - network
  mysqlrouter:
    command: run-mysql-router.sh
  mysqlrouter-service:
    command: start-mysql-router.sh
    daemon: simple
    install-mode: disable
    plugs:
      - network
      - network-bind
  xtrabackup:
    command: usr/bin/xtrabackup
  xbcloud:
    command: usr/bin/xbcloud
    plugs:
      - network
  xbstream:
    command: usr/bin/xbstream
  mysqld-exporter:
    command: start-mysqld-exporter.sh
    daemon: simple
    plugs:
      - network
      - network-bind
parts:
  packages-deb:
    plugin: nil
    stage-packages:
      - mysql-server
      - mysql-router
      - mysql-shell
      - percona-xtrabackup-80
      - util-linux
  wrapper:
    plugin: dump
    source: snap/local
  mysqld-exporter:
    plugin: dump
    # yamllint disable-line rule:line-length
    source: https://github.com/prometheus/mysqld_exporter/releases/download/v0.14.0/mysqld_exporter-0.14.0.linux-amd64.tar.gz
    source-type: tar
    # yamllint disable-line rule:line-length
    source-checksum: sha256/c17402137a4e9745f593127f162c1003298910cb8aa7d05bee3384738de094ae
    organize:
      'mysqld_exporter': usr/bin/mysqld_exporter
    prime:
      - -LICENSE
      - -NOTICE
